site_name: Livres pour enfants

theme:
  name: material
  features:
    - navigation.expand


nav:
  - Introduction: index.md
  - Categories:
    - "Girls empowerment": girls_empowerment.md
    - "Livres sans image": livres_sans_image.md
    - "Pour rire": pour_rire.md
    - "Pour rêver": pour_rever.md
  - Artistes:
    - "Anthony Browne": authors/anthony_browne.md
    - "Kazuo Iwamura": authors/kazuo_iwamura.md
    - "David Wiesner": authors/david_wiesner.md
  - "Par âge":
    - "0-1 ans": 0_1_ans.md
    - "2-3 ans": 2_3_ans.md
    - "4-5 ans": 4_5_ans.md

markdown_extensions:
  - attr_list