site_name: Livres pour enfants

theme:
  name: material
  features:
    - navigation.expand


nav:
  - Introduction: index.md
  - Categories:
    - "Girls empowerment": girls_empowerment.md
    - "Livres sans image": livres_sans_image.md
    - "Pour rire": pour_rire.md
    - "Pour rêver": pour_rever.md
  - Artistes:
    - "Kazuo Iwamura": authors/kazuo_iwamura.md
    - "David Wiesner": authors/david_wiesner.md

markdown_extensions:
  - attr_list