site_name: Livres pour enfants

theme:
  name: material
  features:
    - navigation.expand


nav:
  - Home: index.md
  - "Par auteurs": par_auteurs.md
  # - Artistes:
  #   - "Artist 1": artist_1.md
  - Categories:
    - "Girls empowerment": girls_empowerment.md
    - "Livres sans image": livres_sans_image.md
