from site_livres_enfants_backend.livre import Livre, BooksCategory  

from site_livres_enfants_backend.livres_database.by_authors.kazuo_iwamura import kazuo_iwamura_livres
from site_livres_enfants_backend.livres_database.by_authors.david_wiesner import david_wiesner_livres
from site_livres_enfants_backend.livres_database.by_authors.helen_oxenburry import helen_oxenburry_livres
from .pauline_delabroy_allard import pauline_delabroy_allard_livres
from .anthony_browne import anthony_browne_livres

by_authors_books: list[Livre] = []
by_authors_books.extend(kazuo_iwamura_livres)
by_authors_books.extend(david_wiesner_livres)
by_authors_books.extend(helen_oxenburry_livres)
by_authors_books.extend(pauline_delabroy_allard_livres)
by_authors_books.extend(anthony_browne_livres)
